server:
  port: 8084

spring:
  application:
    name: Spring Projesi Oluşturma

  datasource:
    url: jdbc:postgresql://localhost:5432/bebka
    username: postgres
    password: 1116
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect